### ISSUE TITLE
Regex not accounting for 'H' in 'Http'?

### ISSUE THREAD

**Issue by bhtruong93** [Zhouzi/linkhunter#4]
Trying to beautify a link such as "Http://twitter.com" will result in "Http:/.../twitter.com.  Kinda looks like it has to do with the capital 'H' in the beginning. 

The same thing happens if you do 'HTTP://TWITTER.COM' -> 'HTTP:/.../TWITTER.COM'

**Comment by Zhouzi** [comment]
Thanks for the heads-up @bhtruong93! It's now fixed and shipped with v3.1.2 :)
